// <auto-generated />
using System;
using AdminDashboardApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminDashboardApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdminDashboardApp.Models.Bagian", b =>
                {
                    b.Property<int>("BagianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BagianId"));

                    b.Property<int?>("FungsiId")
                        .HasColumnType("int");

                    b.Property<string>("NamaBagian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BagianId");

                    b.HasIndex("FungsiId");

                    b.ToTable("Bagian");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.JadwalTeknisi", b =>
                {
                    b.Property<int>("JadwalTeknisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JadwalTeknisiId"));

                    b.Property<int?>("BagianId")
                        .HasColumnType("int")
                        .HasColumnName("BagianId");

                    b.Property<int?>("FungsiId")
                        .HasColumnType("int")
                        .HasColumnName("FungsiId");

                    b.Property<TimeSpan?>("JamMulai")
                        .IsRequired()
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("JamSelesai")
                        .IsRequired()
                        .HasColumnType("time(6)");

                    b.Property<int?>("JenisSupportId")
                        .HasColumnType("int");

                    b.Property<string>("NamaKegiatan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RuangRapatId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Tanggal")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserKontak")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserNama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("JadwalTeknisiId");

                    b.HasIndex("BagianId");

                    b.HasIndex("FungsiId");

                    b.HasIndex("JenisSupportId");

                    b.HasIndex("RuangRapatId");

                    b.ToTable("jadwalteknisi");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.JenisSupportJadwal", b =>
                {
                    b.Property<int>("JenisSupportId")
                        .HasColumnType("int");

                    b.Property<int>("JadwalTeknisiId")
                        .HasColumnType("int");

                    b.HasKey("JenisSupportId", "JadwalTeknisiId");

                    b.HasIndex("JadwalTeknisiId");

                    b.ToTable("JenisSupportJadwal");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.RuangRapat", b =>
                {
                    b.Property<int?>("RuangRapatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("RuangRapatId"));

                    b.Property<string>("Lantai")
                        .HasColumnType("longtext");

                    b.Property<string>("NamaGedung")
                        .HasColumnType("longtext");

                    b.Property<string>("NamaRuang")
                        .HasColumnType("longtext");

                    b.HasKey("RuangRapatId");

                    b.ToTable("ruangrapat");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.Teknisi", b =>
                {
                    b.Property<int>("TeknisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeknisiId"));

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.Property<string>("RuangRapatUtama")
                        .HasColumnType("longtext");

                    b.Property<string>("Skill")
                        .HasColumnType("longtext");

                    b.HasKey("TeknisiId");

                    b.ToTable("teknisi");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.TeknisiJadwal", b =>
                {
                    b.Property<int>("TeknisiId")
                        .HasColumnType("int");

                    b.Property<int>("JadwalTeknisiId")
                        .HasColumnType("int");

                    b.HasKey("TeknisiId", "JadwalTeknisiId");

                    b.HasIndex("JadwalTeknisiId");

                    b.ToTable("TeknisiJadwal");
                });

            modelBuilder.Entity("Fungsi", b =>
                {
                    b.Property<int?>("FungsiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fungsi_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("FungsiId"));

                    b.Property<string>("NamaFungsi")
                        .HasColumnType("longtext")
                        .HasColumnName("nama_fungsi");

                    b.HasKey("FungsiId");

                    b.ToTable("Fungsi");
                });

            modelBuilder.Entity("JenisSupport", b =>
                {
                    b.Property<int>("JenisSupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JenisSupportId"));

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NamaJenisSupport")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("jenissupport");

                    b.HasKey("JenisSupportId");

                    b.ToTable("jenissupport");
                });

            modelBuilder.Entity("PeminjamanAlat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BagianId")
                        .HasColumnType("int");

                    b.Property<string>("NamaAlat")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BagianId");

                    b.ToTable("peminjamanalat");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.Bagian", b =>
                {
                    b.HasOne("Fungsi", "Fungsi")
                        .WithMany("Bagians")
                        .HasForeignKey("FungsiId");

                    b.Navigation("Fungsi");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.JadwalTeknisi", b =>
                {
                    b.HasOne("AdminDashboardApp.Models.Bagian", "Bagian")
                        .WithMany()
                        .HasForeignKey("BagianId");

                    b.HasOne("Fungsi", "Fungsi")
                        .WithMany()
                        .HasForeignKey("FungsiId");

                    b.HasOne("JenisSupport", null)
                        .WithMany("JadwalTeknisis")
                        .HasForeignKey("JenisSupportId");

                    b.HasOne("AdminDashboardApp.Models.RuangRapat", "RuangRapat")
                        .WithMany()
                        .HasForeignKey("RuangRapatId");

                    b.Navigation("Bagian");

                    b.Navigation("Fungsi");

                    b.Navigation("RuangRapat");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.JenisSupportJadwal", b =>
                {
                    b.HasOne("AdminDashboardApp.Models.JadwalTeknisi", "JadwalTeknisi")
                        .WithMany("JenisSupportJadwals")
                        .HasForeignKey("JadwalTeknisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JenisSupport", "JenisSupport")
                        .WithMany("JenisSupportJadwals")
                        .HasForeignKey("JenisSupportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JadwalTeknisi");

                    b.Navigation("JenisSupport");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.TeknisiJadwal", b =>
                {
                    b.HasOne("AdminDashboardApp.Models.JadwalTeknisi", "JadwalTeknisi")
                        .WithMany("TeknisiJadwals")
                        .HasForeignKey("JadwalTeknisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminDashboardApp.Models.Teknisi", "Teknisi")
                        .WithMany("TeknisiJadwals")
                        .HasForeignKey("TeknisiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JadwalTeknisi");

                    b.Navigation("Teknisi");
                });

            modelBuilder.Entity("PeminjamanAlat", b =>
                {
                    b.HasOne("AdminDashboardApp.Models.Bagian", "Bagian")
                        .WithMany()
                        .HasForeignKey("BagianId");

                    b.Navigation("Bagian");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.JadwalTeknisi", b =>
                {
                    b.Navigation("JenisSupportJadwals");

                    b.Navigation("TeknisiJadwals");
                });

            modelBuilder.Entity("AdminDashboardApp.Models.Teknisi", b =>
                {
                    b.Navigation("TeknisiJadwals");
                });

            modelBuilder.Entity("Fungsi", b =>
                {
                    b.Navigation("Bagians");
                });

            modelBuilder.Entity("JenisSupport", b =>
                {
                    b.Navigation("JadwalTeknisis");

                    b.Navigation("JenisSupportJadwals");
                });
#pragma warning restore 612, 618
        }
    }
}
